# -*- coding: utf-8 -*-
"""Nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nc2YF9zYaWv-AGtANHqy2OOmq85FqFbI
"""

!pip install Sastrawi

import pandas as pd
import re
import string
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

nltk.download('stopwords')
nltk.download('punkt_tab')

"""### **DATASET 1**"""

from google.colab import files
files.upload()

df1 = pd.read_csv('dataset1_gojek.csv')

df1.head()

# Buang Data Null/Duplicate Values
df1 = df1.dropna()
df1 = df1.drop_duplicates()

# Cek Distribusi Label
print(df1['rate'].value_counts())
print(df1['rate'].value_counts(normalize=True).round(3))

# Cleaning
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'\d+', '', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df1['clean_review'] = df1['review'].apply(clean_text)

# Stopword Removal
important_words = {
    'tidak', 'tak', 'bukan', 'belum', 'jangan', 'tanpa',
    'kurang', 'gagal', 'susah', 'sulit', 'males', 'malas',
    'buruk', 'jelek', 'parah', 'lambat', 'lemot', 'bohong'
}

stop_words = set(stopwords.words('indonesian')) - important_words

def preprocess_text(text):
    words = text.split()
    words = [w for w in words if w not in stop_words]
    words = [w for w in words if len(w) > 1]
    return " ".join(words)

df1['processed_review'] = df1['clean_review'].apply(preprocess_text)
df1['label'] = df1['rate'].map({'positive': 1, 'negative': 0})

# Split
X = df1['processed_review']
y = df1['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# TF-IDF + Bigram
tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1,2))
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

ratio_df1 = df1['label'].value_counts(normalize=True).sort_index().values

# Model
naive_bayes = MultinomialNB(class_prior=ratio_df1)
naive_bayes.fit(X_train_tfidf, y_train)
y_pred_nb = naive_bayes.predict(X_test_tfidf)

logistic_regression = LogisticRegression(max_iter=1000, class_weight='balanced')
logistic_regression.fit(X_train_tfidf, y_train)
y_pred_lr = logistic_regression.predict(X_test_tfidf)

svm = SVC(kernel='linear', class_weight='balanced', random_state=42)
svm.fit(X_train_tfidf, y_train)
y_pred_svm = svm.predict(X_test_tfidf)

rf = RandomForestClassifier(n_estimators=50, class_weight='balanced', random_state=42, n_jobs=-1)
rf.fit(X_train_tfidf, y_train)
y_pred_rf = rf.predict(X_test_tfidf)

# Confusion Matrix
fig, ax = plt.subplots(2, 2, figsize=(12, 8))

ConfusionMatrixDisplay.from_predictions(y_test, y_pred_nb,  ax=ax[0][0], cmap="Blues", values_format='d')
ax[0][0].set_title("Naive Bayes - Dataset 1")

ConfusionMatrixDisplay.from_predictions(y_test, y_pred_lr,  ax=ax[0][1], cmap="Blues", values_format='d')
ax[0][1].set_title("Logistic Regression - Dataset 1")

ConfusionMatrixDisplay.from_predictions(y_test, y_pred_svm, ax=ax[1][0], cmap="Blues", values_format='d')
ax[1][0].set_title("SVM - Dataset 1")

ConfusionMatrixDisplay.from_predictions(y_test, y_pred_rf,  ax=ax[1][1], cmap="Blues", values_format='d')
ax[1][1].set_title("Random Forest - Dataset 1")

plt.tight_layout()
plt.show()

# Evaluasi
print("Naive Bayes")
print("Accuracy  : {:.4f}".format(accuracy_score(y_test, y_pred_nb)))
print("Precision : {:.4f}".format(precision_score(y_test, y_pred_nb, zero_division=0)))
print("Recall    : {:.4f}".format(recall_score(y_test, y_pred_nb, zero_division=0)))
print("F1-score  : {:.4f}".format(f1_score(y_test, y_pred_nb, zero_division=0)))
print(classification_report(y_test, y_pred_nb, target_names=['negative', 'positive'], zero_division=0))

print("\nLogistic Regression")
print("Accuracy  : {:.4f}".format(accuracy_score(y_test, y_pred_lr)))
print("Precision : {:.4f}".format(precision_score(y_test, y_pred_lr, zero_division=0)))
print("Recall    : {:.4f}".format(recall_score(y_test, y_pred_lr, zero_division=0)))
print("F1-score  : {:.4f}".format(f1_score(y_test, y_pred_lr, zero_division=0)))
print(classification_report(y_test, y_pred_lr, target_names=['negative', 'positive'], zero_division=0))

print("\nSVM")
print("Accuracy  : {:.4f}".format(accuracy_score(y_test, y_pred_svm)))
print("Precision : {:.4f}".format(precision_score(y_test, y_pred_svm, zero_division=0)))
print("Recall    : {:.4f}".format(recall_score(y_test, y_pred_svm, zero_division=0)))
print("F1-score  : {:.4f}".format(f1_score(y_test, y_pred_svm, zero_division=0)))
print(classification_report(y_test, y_pred_svm, target_names=['negative', 'positive'], zero_division=0))

print("\nRandom Forest")
print("Accuracy  : {:.4f}".format(accuracy_score(y_test, y_pred_rf)))
print("Precision : {:.4f}".format(precision_score(y_test, y_pred_rf, zero_division=0)))
print("Recall    : {:.4f}".format(recall_score(y_test, y_pred_rf, zero_division=0)))
print("F1-score  : {:.4f}".format(f1_score(y_test, y_pred_rf, zero_division=0)))
print(classification_report(y_test, y_pred_rf, target_names=['negative', 'positive'], zero_division=0))

"""### **DATASET 2**"""

from google.colab import files
files.upload()

df2 = pd.read_csv('dataset2_gojek.csv')

df2.head()

# Cleaning
df2.columns = df2.columns.str.strip()
df2 = df2.dropna()
df2 = df2.drop_duplicates()

# Buang Rating Netral (3), Lalu Convert Ke Label Biner
# 1 & 2 = negative
# 3 = not used
# 4 & 5 = positive
df2 = df2[df2['score'] != 3]
df2['label'] = df2['score'].apply(lambda x: 0 if x <= 2 else 1)

# Cek Distribusi Label
print(df2['label'].value_counts())
print(df2['label'].value_counts(normalize=True).round(3))

# Cleaning + Preprocessing Text
df2['clean_review'] = df2['content'].apply(clean_text)
df2['processed_review'] = df2['clean_review'].apply(preprocess_text)

# Split
X = df2['processed_review']
y = df2['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# TF-IDF + Bigram
tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1,2))
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

ratio_df2 = df2['label'].value_counts(normalize=True).sort_index().values

# Model
naive_bayes = MultinomialNB(class_prior=ratio_df2)
naive_bayes.fit(X_train_tfidf, y_train)
y_pred_nb = naive_bayes.predict(X_test_tfidf)

logistic_regression = LogisticRegression(max_iter=1000, class_weight='balanced')
logistic_regression.fit(X_train_tfidf, y_train)
y_pred_lr = logistic_regression.predict(X_test_tfidf)

svm = SVC(kernel='linear', class_weight='balanced', random_state=42)
svm.fit(X_train_tfidf, y_train)
y_pred_svm = svm.predict(X_test_tfidf)

rf = RandomForestClassifier(n_estimators=50, class_weight='balanced', random_state=42, n_jobs=-1)
rf.fit(X_train_tfidf, y_train)
y_pred_rf = rf.predict(X_test_tfidf)

# Confusion Matrix
fig, ax = plt.subplots(2, 2, figsize=(12, 8))

ConfusionMatrixDisplay.from_predictions(y_test, y_pred_nb,  ax=ax[0][0], cmap="Blues", values_format='d')
ax[0][0].set_title("Naive Bayes - Dataset 2")

ConfusionMatrixDisplay.from_predictions(y_test, y_pred_lr,  ax=ax[0][1], cmap="Blues", values_format='d')
ax[0][1].set_title("Logistic Regression - Dataset 2")

ConfusionMatrixDisplay.from_predictions(y_test, y_pred_svm, ax=ax[1][0], cmap="Blues", values_format='d')
ax[1][0].set_title("SVM - Dataset 2")

ConfusionMatrixDisplay.from_predictions(y_test, y_pred_rf,  ax=ax[1][1], cmap="Blues", values_format='d')
ax[1][1].set_title("Random Forest - Dataset 2")

plt.tight_layout()
plt.show()

# Evaluasi
print("Naive Bayes")
print("Accuracy  : {:.4f}".format(accuracy_score(y_test, y_pred_nb)))
print("Precision : {:.4f}".format(precision_score(y_test, y_pred_nb, zero_division=0)))
print("Recall    : {:.4f}".format(recall_score(y_test, y_pred_nb, zero_division=0)))
print("F1-score  : {:.4f}".format(f1_score(y_test, y_pred_nb, zero_division=0)))
print(classification_report(y_test, y_pred_nb, target_names=['negative', 'positive'], zero_division=0))

print("\nLogistic Regression")
print("Accuracy  : {:.4f}".format(accuracy_score(y_test, y_pred_lr)))
print("Precision : {:.4f}".format(precision_score(y_test, y_pred_lr, zero_division=0)))
print("Recall    : {:.4f}".format(recall_score(y_test, y_pred_lr, zero_division=0)))
print("F1-score  : {:.4f}".format(f1_score(y_test, y_pred_lr, zero_division=0)))
print(classification_report(y_test, y_pred_lr, target_names=['negative', 'positive'], zero_division=0))

print("\nSVM")
print("Accuracy  : {:.4f}".format(accuracy_score(y_test, y_pred_svm)))
print("Precision : {:.4f}".format(precision_score(y_test, y_pred_svm, zero_division=0)))
print("Recall    : {:.4f}".format(recall_score(y_test, y_pred_svm, zero_division=0)))
print("F1-score  : {:.4f}".format(f1_score(y_test, y_pred_svm, zero_division=0)))
print(classification_report(y_test, y_pred_svm, target_names=['negative', 'positive'], zero_division=0))

print("\nRandom Forest")
print("Accuracy  : {:.4f}".format(accuracy_score(y_test, y_pred_rf)))
print("Precision : {:.4f}".format(precision_score(y_test, y_pred_rf, zero_division=0)))
print("Recall    : {:.4f}".format(recall_score(y_test, y_pred_rf, zero_division=0)))
print("F1-score  : {:.4f}".format(f1_score(y_test, y_pred_rf, zero_division=0)))
print(classification_report(y_test, y_pred_rf, target_names=['negative', 'positive'], zero_division=0))

def predict_sentiment(text, model, tfidf):
    cleaned = clean_text(text)
    processed = preprocess_text(cleaned)
    vect = tfidf.transform([processed])
    pred = model.predict(vect)[0]
    return "positive" if pred == 1 else "negative"

while True:
    user_input = input("\nInput review (ketik 'exit' untuk keluar): ")

    if user_input.lower() == 'exit':
        print("ThankYou")
        break

    nb_pred  = predict_sentiment(user_input, naive_bayes, tfidf)
    lr_pred  = predict_sentiment(user_input, logistic_regression, tfidf)
    svm_pred = predict_sentiment(user_input, svm, tfidf)
    rf_pred  = predict_sentiment(user_input, rf, tfidf)

    print("\nHasil Prediksi:")
    print("Naive Bayes         :", nb_pred)
    print("Logistic Regression :", lr_pred)
    print("SVM                 :", svm_pred)
    print("Random Forest       :", rf_pred)
